name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install backend dependencies
        working-directory: ./api
        run: |
          pip install -r requirements.txt || true
          python -m uvicorn main:app --reload
          echo "Python requirements installed"

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: |
          npm install --legacy-peer-deps
          echo "NPM requirements installed"

      - name: Update browserslist DB
        working-directory: ./frontend
        run: |
          npx update-browserslist-db@latest
          npm install caniuse-lite@latest --legacy-peer-deps
          echo "Browserslist DB updated"

      - name: Run frontend tests
        working-directory: ./frontend
        run: |
          npm run build