name: Build and Deploy

on:
  push:
    branches:
      - main  # Change this to your branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # You can adjust the version of Python you're using

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set environment variables from GitHub Secrets
      - name: Set environment variables
        run: |
          echo "ATLAS_URI=${{ secrets.ATLAS_URI }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> $GITHUB_ENV
          echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV

      # Step 5: Run your application (or build the project)
      - name: Run the application
        run: |
          uvicorn api.main:app --reload  # Replace with the actual command to start your app
